# Generated by Django 4.2.6 on 2023-12-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='image',
            field=models.ImageField(default='avtar1.png', upload_to='image'),
        ),
    ]
