# Generated by Django 4.2.7 on 2023-12-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_profileinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='image',
            field=models.ImageField(default='media/image/avtar1.png', upload_to='media/image'),
        ),
    ]
